###
GET http://localhost:8000/products

###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Curso do Zero a Programador",
    "price": 1000
}

###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Consultoria de engenharia de software",
    "price": 1459.59
}

###
PUT  http://localhost:8000/products/967c4367-b845-4aca-af60-57a21a0baf8c
Content-Type: application/json

{
    "name": "Criação de Sass",
    "price": 1552.50
}